# Generated by Django 4.1.5 on 2023-01-19 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_automobile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Automobile',
        ),
        migrations.DeleteModel(
            name='person',
        ),
    ]
